### ISSUE TITLE
Is a board seat awarded to a person or an organization?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/governance#3]

**Comment by jmchilton** [comment]
Traditionally this is done by organization, but I want to (admitting my self-interest upfront) put in an argument for people. I think the reason this effort succeeded where others have failed is because it has been very engineer-driven. Many standardization efforts turn into competing efforts between organizations or even continents, but I think we have managed to avoid the fights between organizations with competing self interests because the engineers collaborating have worked in a good faith way toward the common good. It also has fit well with our do-ocratic approach up until now.

**Comment by stain** [comment]
+1 for individuals, which gives longer-term commitment. It also gives a better chance of reducing political fights as organizations come in different sizes.

Organizations can rather become partners, and have a say (but not a vote). Someone from a partner who engages actively and cares about CWL (rather than just his organization) will become eligible to be voted in to the board - but so would someone from the "outside".

**Comment by mr-c** [comment]
Another variation on the members = individuals approach are rules about limiting the number of individuals who have the same employer to avoid takeover via hiring.

**Comment by mr-c** [comment]
As per the Software Freedom Conservancy rules, seats are for individuals but no more than one person from any company/institution may be on the board.
